import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def execute():
	custom_fields = {
		"Supplier": [
			dict(
				fieldname="custom_tds",
				label="TDS",
				fieldtype="Tab Break",
				insert_after="language",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_pan_number",
				label="Pan Number",
				fieldtype="Data",
				insert_after="custom_tds",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_has_withholding_tax",
				label="Has Withholding Tax",
				fieldtype="Check",
				insert_after="custom_pan_number",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_is_aadhar_link_compliance",
				label="Is Aadhar Link Compliance",
				fieldtype="Check",
				insert_after="custom_has_withholding_tax",
				depends_on="custom_has_withholding_tax",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_taxes",
				label="Taxes",
				fieldtype="Table",
				insert_after="custom_lower_tds_certificate_rate",
				depends_on="custom_has_withholding_tax",
				options="Supplier Withholding Tax",
				read_only=0,
				print_hide=0,
			)
		],
		"Purchase Invoice Item": [
			dict(
				fieldname="custom_section_break_ricb4",
				label="Taxwithholding Details",
				fieldtype="Section Break",
				insert_after="is_free_item",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_tax_withholding_category",
				label="Tax Withholding Category",
				fieldtype="Link",
				insert_after="apply_tds",
				options="Tax Withholding Category",
				read_only=0,
				print_hide=0,
			),
		],
		"Purchase Receipt Item": [
			dict(
				fieldname="custom_section_break_ricb4",
				label="Taxwithholding Details",
				fieldtype="Section Break",
				insert_after="is_free_item",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_tax_withholding_category",
				label="Tax Withholding Category",
				fieldtype="Link",
				insert_after="apply_tds",
				options="Tax Withholding Category",
				read_only=0,
				print_hide=0,
			),
		],
		"Purchase Order Item": [
			dict(
				fieldname="custom_section_break_ricb4",
				label="Taxwithholding Details",
				fieldtype="Section Break",
				insert_after="is_free_item",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_tax_withholding_category",
				label="Tax Withholding Category",
				fieldtype="Link",
				insert_after="apply_tds",
				options="Tax Withholding Category",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="tds_amount",
				label="Tax Withholding Amount",
				fieldtype="Currency",
				insert_after="custom_tax_withholding_category",
				read_only=1,
				print_hide=0,
			),
		],
		"Tax Withholding Rate": [
			dict(
				fieldname="custom_non_compliance_of",
				label="Non Compliance of",
				fieldtype="Section Break",
				insert_after="cumulative_threshold",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_pan_rate",
				label="No Pan Rate",
				fieldtype="Float",
				insert_after="custom_non_compliance_of",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="custom_no_aadhaar_rate",
				label="No Aadhaar Link Rate",
				fieldtype="Float",
				insert_after="custom_pan_rate",
				read_only=0,
				print_hide=0,
			),
		],
		"Advance Taxes and Charges": [
			dict(
				fieldname="included_in_print_rate",
				label="Included in Print Rate",
				fieldtype="Check",
				insert_after="currency",
				read_only=1,
				hidden=1,
				print_hide=1,
			),
			dict(
				fieldname="tax_amount_after_discount_amount",
				label="Tax Amount After Discount Amount",
				fieldtype="Currency",
				insert_after="tax_amount",
				read_only=1,
				hidden=1,
				print_hide=1,
			),
			dict(
				fieldname="base_tax_amount_after_discount_amount",
				label="Base Tax Amount After Discount Amount",
				fieldtype="Currency",
				insert_after="tax_amount",
				read_only=1,
				hidden=1,
				print_hide=1,
			),
		],
		"Payment Entry": [
			dict(
				fieldname="currency",
				label="Currency",
				fieldtype="Link",
				insert_after="party_name",
				options="Currency",
				read_only=1,
				print_hide=0,
			),
			dict(
				fieldname="section_break_payment_entry_item",
				label="Items",
				fieldtype="Section Break",
				insert_after="paid_to_account_balance",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="advance_payment_percentage",
				label="Advance Payment Percentage",
				fieldtype="Percent",
				insert_after="section_break_payment_entry_item",
				read_only=0,
				print_hide=0,
			),
			dict(
				fieldname="items",
				label="Items",
				fieldtype="Table",
				insert_after="advance_payment_percentage",
				options="Payment Entry Item",
				read_only=1,
				print_hide=0,
			),
			dict(
				fieldname="total",
				label="Total",
				fieldtype="Currency",
				insert_after="items",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="base_total",
				label="Base Total",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="net_total",
				label="Net Total",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="base_net_total",
				label="Base Net Total",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="rounding_adjustment",
				label="Rounding Adjustment",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="base_rounding_adjustment",
				label="Base Rounding Adjustment",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="taxes_and_charges_added",
				label="Taxes and Charges Added",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="base_taxes_and_charges_added",
				label="Base Taxes and Charges Added",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="taxes_and_charges_deducted",
				label="Taxes and Charges Deducted",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="base_taxes_and_charges_deducted",
				label="Base Taxes and Charges Deducted",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="grand_total",
				label="Grand Total",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
			dict(
				fieldname="base_grand_total",
				label="Base Grand Total",
				fieldtype="Currency",
				insert_after="total",
				options="currency",
				read_only=1,
				print_hide=1,
				hidden=1,
			),
		],
	}

	create_custom_fields(custom_fields)